---
title: "Proposal"
subtitle: "Innovedum - AI in teaching and learning"
format: docx
bibliography: prop-innovedum-ai.bib
---

# Resources (not part of project proposal)

## Evaluation criteria (boxes to tick)

- [ ] Innovation for teaching and learning at ETH beyond the normal ongoing course development process
- [ ] Structured didactic and conceptual project design
- [ ] Inclusion of the **student perspective** in the project design and the planned project implementation
- [ ] Ensure the flexible usability and accessibility of the new learning media and materials (**e-accessibility**)
- [ ] Prospect of success based on successful delivery of the project plan (realistic implementation plan: clear and convincing project goals and project plan, necessary resources are available)
- [ ] Sustainability / continued use of the project results beyond the end of the project (possibility **follow-up projects**)
- [ ] Transferability and possible dissemination of the educational innovation to a wider audience (e.g. other universities, course or departments)
- [ ] Project communication: Project insights will be made accessible to interested ETH lecturers.
- [ ] Coherent **evaluation plan**
- [ ] If applicable: Plan for managing personal data
- [ ] Appropriateness of the planned costs (such as the expected efforts, expect results in relation to the number of students affected)
- [ ] Only Focus topics: Project investigates aspects of a specific focus topic
- [ ] Funding for summer or winter schools is only possible if new teaching concepts are tested within them. Furthermore, repeated implementation and sustainability of the concepts must be guaranteed

## Blog: 10 things to consider when applying for an Innovedum project

- Identify the correct grant scheme. tick
- State your idea clearly. tick
- Give us your context. tick
- Feature the voice of learners. TODO
- Demonstrate that you talked to educators and didactic experts. tick
- Present a realistic project plan. TODO
- Assume supportive reviewers
- Put your didactic innovations front and center. Tick
- Think beyond your project. TODO
- Share your learnings. Tick

https://blogs.ethz.ch/letblog/2021/09/03/10-things-to-consider-when-applying-for-an-innovedum-project/


## Focus on Exploring AI in Academic Writing: Two innovative Innovedum projects

Two AI project examples recently funded through Innovedum.

https://blogs.ethz.ch/letblog/2023/09/18/focus-on-exploring-ai-in-academic-writing-two-innovative-innovedum-projects/

# Project Application Innovedum

- Proposalnumber: 
- Project type: Focal Point Project
- Focus topic: AI in Teaching and Learning
- Start date: 2024-01-01
- End date: 2025-06-30
- Extended: 
- Type of proposal

# Project title

- English: 
- German: 

# Institute

- Institute:
- Department:
- Postal address

# Applicants

- Main applicant:
- Project manager:
- Project partner:

# 1. Project summary

## 1.1. Describe the project in 1-2 sentences (max. 400 characters; 57 to 90 words; will be published in the project database)

TODO: Write up at the end

## 1.2. Project summary (ca. 200 words; will be published in the project database).

TODO: Write up at the end

# 2. Consultation

## 2.1. Student involvement: Describe whether and how students were involved in the preparation and review of this project application. How will students be involved in project implementation?

The proposal was shared with students that participated in our first class (rbtl: Research beyond the lab) in spring semester 2022 to get general feedback about elements they found difficult to understand during class. For this purpose, we also used the results of the student evaluation survey from 2022, which 13/14 students completed. 

The project implementation will be in coordination and collaboration with students that participate in our class (rbtl: Research beyond the lab) in spring semester 2024. They will be directly involved in the the project implementation as they use the proposed solutions and provide interim feedback. 

## 2.2. Who advised you on your project and/or who gave you feedback on it (e.g. LET / Educational Developer(s) / department(s) / other faculty / other)?

An initial project idea was shared with Daniela Eawason as a response to the announcenment of the new focal point topic. We requested to share our idea with Katrin Bentel (LET) who we have been continously been in touch about open science ideas and computational reproducibility for about 1.5 years. We then shared our proposal with Kathrin Bentel and Julia Kehl (both LET) who we met personally to discuss. Their advise was integrated into a draft proposal, which was shared once more including technical questions about the submission platform. 

The draft proposal was also shared with employees of the Global Health Engineering group. Elizabeth Tilley (head of group) and Mian Zhong (Data Scientist and expert in Natural Language Processing) provided detailed feedback on the proposal. 

# 3. Project description

## 3.1. Starting position: Describe the current situation. What didactic and disciplinary challenges does your project address? (max 365/250 words). Info: Show the relevance of and the need leading to the project. List (if applicable) preliminary work to remedy the situation.

At the Global Health Engineering group, we teach a class (rbtl: Research Beyond the Lab) on how to conduct a research project out of the lab and apply open science principles and effective research data management. Amongst other data science tools, students learn to use the R statistical programming language, for which we assume no prior knowledge.

With the rise of Large Language Models (LLMs) and associated tools such classes run the risk of not providing added value to students if teachers miss out on including LLMs in their teaching. Students can now auto-generate solutions to programming assessments with high accuracy [@denny2023computing]. A structured, defined and open approach is needed to encourage students to use such tools responsibly while teachers can enhance the learning experience and increase their efficiency and productivity. 

This project addresses the following didactic and disciplinary challenges in four work packages.

### WP 1 - Responsible AI use

**Challenge:** Ensuring students use AI responsibly and effectively while developing their problem-solving and programming skills.

### WP 2 - AI as a tutor / Getting help online

**Challenge:** Helping students navigate the overwhelming amount of information available online to receive solutions to their coding problems.

### WP 3 - Enhance learning

**Challenge:** Didactic challenge: Enhancing retrieval practice, improving student learning, and enriching the learning experience in a time-constraint environment.

### WP 4 - Student assessment (exams)

**Challenge**:  Applying the knowledge and skills gained throughout the course to analyze data, draw conclusions, and demonstrate programming proficiency in a time-limited exam setting that allows for the use of LLMs.

## 3.2. Project goals: List the concrete project goals. (250 words). Info: 3 to 5 clear measurable objectives. Please fill the fields in German and English. The information will be published in Innovedum Public. 

### WP 1 - Responsible AI use

**Challenge:** Ensuring that students use AI responsibly and effectively, while still developing their own problem-solving and programming skills.

We will teach students how to use AI tools and discuss the ethical implications of using LLMs in programming, including the potential for over-reliance on AI-generated solutions and the importance of developing problem-solving skills.

**Goal:** Integrate Large Language Models (LLMs) into lectures and require it as a mandatory tool to use in class. 

**Objective 1:** Within 9 months after the start of the project an usage usage policy and associated teaching module is being re-used by other classes at ETH or beyond. 

**Activity:** 3-hour module introducing LLMs, ethical considerations and prompting AI for different use cases.

**Activity:** Develop a usage policy to make students aware of the limitations of LLMs.

**Activity:** Require students to share links to their prompts and reflect on the usage of AI for each assessment.

### WP 2 - AI as a tutor / Getting help

**Challenge:** Helping students navigate the overwhelming amount of information available online to receive solutions to their individual coding problems from programming tasks.

LLMs have shown great potential to provide coding support from plain language descriptions. Once students know how to phrase an appropriate prompt, they will receive functional examples that are coherent. 

**Goal:** Use LLMs to provide code examples and support novices to find answers to programming tasks.

**Objective 2:** Ensure that 90% of AI-generated code examples and solutions are accurate, relevant, and helpful for novice programmers.

**Activity:** Create a collection of 60 problem statements (20 for each level of complexity: low, medium, high) for R programming tasks, along with their respective AI prompts.

**Activity** Identify appropriate open format to publish problem statements and prompts under an open and permissive license as a prompt library.

**Objective 3** Identify the experiences and perceived advantages of using AI tools for learning programming with R.

**Activity:** Conduct a student survey prior to the class to identify students’ prior knowledge in the R programming language and programming in general.

**Activity:** Conduct student surveys throughout the course to evaluate the experience of using AI tools for learning programming with R.

### WP 3 - Enhance learning

**Challenge:** Enhancing retrieval practice, improving student learning, and enriching the learning experience in a time-constrained environment.

Preparing up-to-date formative assessments and authentic examples requires much time and thought. LLMs show great potential to automate parts of this process. Additionally, AI can serve as a creative engine to prepare analogies that support students in class, further enriching the learning experience [@mollick2023assigning].

**Goal:** Use LLMs to create low-stakes tests for formative assessments (faded examples / scaffolding, Parsons problems, multiple choice quizzes). 

**Objective 3:** Reduce required time for generating formative assessments for R programming concepts by 90%. 

**Activity:** For each class module that teaches R programming concepts, use LLMs to design formative assessments.

**Activity:** Write three formative assessments without the support of LLMs and compare the time requirements to those prepared with the support of AI.

**Activity:** Write tutorials using the learnR for developed formative assessments and publish learnR tutorials as open-source code through GitLab/GitHub using open and permissive licenses (e.g. CC0, CC-BY, Hippocratic License, MIT License)

### WP 4 - Student assessment (exams)

**Challenge**: Applying the knowledge and skills gained throughout the course to analyze data, draw conclusions, and demonstrate programming proficiency in a time-limited exam setting that allows for the use of LLMs.

**Goal:** Develop a technical programming exam that allows students to use LLMs. 

**Objective 4.1:** Create a set of 10-15 exam questions that cover a range of R programming concepts, techniques, and LLM applications, ensuring that at least 80% of the course material is represented in the questions.

**Objective 4.2:** Develop a grading rubric with clear criteria for assessing students' programming proficiency, problem-solving skills, and LLM usage. 

## 3.3. Project progression: Describe the progression of the project (421/300 words). Info box: Describe the different phases of the project.

### Phase 0 - prior to project funding
 
We will implement this project in a class we teach in Spring Semester 2024. Therefore, it is essential to include information about the usage of AI for the class in the course catalogue. Phase 0 has already started as the correction phase for Spring Semester 2024 ends by 13.10.2023. The catalogue information needs to provide enough detail for students to be aware of the usage of AI. However, it also needs to ensure that if the project proposal is not funded, the class can go ahead as published in the course catalogue. 

We are aware of several other initiatives around the use of AI in teaching and learning at ETH. In addition to communicating the project ideas with the Innovedum and LET team, we are actively reaching out to other professionals at ETH who will contribute to building a community of practice, including Manuel Sudau, Educational Developer with LET, Dennis Kochmann at D-MAVT, Christian Franck at D-ITET, Meike Akveld & Andreas Steiger at D-MATH and their product STACK, and lastly the applicants for the most recently funded Innovedum projects with a focus on exploring AI in academic writing (Lucio Isa & Melanie Paschke).

### Phase 1 - human resources and choice of AI tools

The first phase of the project will identify a suitable candidate (Scientific Assistant) to support the project during its implementation phase. Further, the exact choice of AI tools will be made during this phase. Our thinking at the moment is to ask students to use free versions of Perplexity (perplexity.ai), an AI tool that allows the GPT-4 LLM to be used for free.

### Phase 2 - development of course material

While the syllabus and overall objectives for each module of the class will be defined at the outset of the class starting at the end of February 2024,, course material will be prepared flexibly, allowing for the inclusion of learnings from the use of AI models.

### Phase 3 - sharing and dissemination

Once the class is completed, the project team will analyse and compile all material that was generated as part of the work packages. Student surveys will be analysed and results presented back to the scientific community. Details about project communication are covered in section 4.2.

### Phase 4 - integration of learning into future course material

As a final phase, the learnings from the project will be integrated into material for the next class in Spring Term 2025 and other classes that teach programming concepts.

## 3.4. Timetable and milestones

TODO: Add in online form.

## 3.5. Teaching/Learning concept: Explain the didactic principles (e.g. experiences, theories and methods) which underpin your project. (279/300 words). Explain the didactic methodology that underpins the project. This can be your own experience (of that of other lectures) of didactic theories and methods from the literature. 

The idea of using AI to help students with coding problems in R is based on the premise that novices in programming struggle to find help online, and AI tools can provide better code examples if students are taught how to use the relevant prompts. Several didactic theories and methods underpin this idea:

1. **Co-creation and collaboration**: Co-creation in AI-assisted learning involves students working with AI tools to solve problems and learn new concepts. This approach has been explored in studies such as the one on AI-generated programming code in higher education [@jonsson2022cracking]. The study found that AI tools can facilitate understanding and learning and influence creative processes by promoting reflection and exploring alternative solutions. This aligns with the didactic theory of constructivism, which emphasizes that learners actively construct their understanding and knowledge through experiences and interactions.

2. **Personalized learning**: AI tools can offer personalized learning experiences by adapting to individual students' needs, preferences, and learning styles. This approach is supported by the idea that learners have different ways of processing information and that tailored instruction can lead to better learning outcomes [@kaiss2023effectiveness]. It is connected to self-determination theory, which defines three drivers of intrinsic motivation (competence, autonomy, relatedness), all positively impacted by personalized learning.

3. **Connectivism:** Within the classroom, we will engage and interact with the AI tools as a class, in small groups, and individually. The newest feature of Perplexity allows people to have shared Collections of prompt threads. It enables people to craft prompts together, share them with others, and make them public. This supports the theory of connectivism, which emphasizes the importance of networks, social interactions, and the use of technology in the learning process.

## 3.6. Target group(s)

- done in online form 

## 3.7. Effects of the project: Describe the innovative aspects of your project and describe its expected effects and added value for teaching and learning at ETH for all of the following: (167/250 words). These aspects should be different from the normal advancement of teaching. Further benefits and effects can also be listed here.

Above the measurable objectives, the over-arching effect of this project is to shift the culture around AI from shame and secrecy to one that promotes and embraces the practical and enjoyable aspects of this emerging technology. Through this project, we demonstrate to educators who may still be sceptical of AI that it has a place in teaching and allows students and teachers to spend more time learning, discussing, and engaging and less time searching and running failed code. 

### Students

- being aware of the limitations of using AI
- being aware of the responsibility for using AI and critically evaluating all its output
- learning how to use AI for learning a new programming language
- learning how to use AI for debugging code

### Faculty

- learning how to use AI to deliver more engaging classes
- demonstrating the time-saving benefits related to assignment and exam preparation

### The entire degree programme

- learning how to use AI
- embracing a culture of AI use
- belonging to a community of practice for use of AI in teaching and learning


## 3.8. Evaluation strategy: Describe the evaluation strategy you will use to check achievement of project goals (see 3.2) and effects on teaching (see 3.7). (250 words)

To check the achievement of project goals and related objectives, we will work with Nore Dietmann from LET to support us in developing a student evaluation survey that explicitly targets WP1 Responsible AI use, and WP2 AI as a tutor. One survey will be implemented after teaching a specific 3-hour AI module. Another survey at the end of the course, and finally a follow-up survey 6 months after course completion. In combindation, these three surveys will help identify student satisfaction, improve course material, but also ensure that the expected innovate effects are taking place.  

The specific evaluation of each objective is shown in Table X. 
- What approaches will you use?
- Are you planning measures for identifying interim results? If so, how will these results flow back into the project?

Objective 1: Within 9 months after the start of the project an usage usage policy and associated teaching module is being re-used by other classes at ETH or beyond.

Objective 2: (Ensure that 90% of AI-generated code examples and solutions are accurate, relevant, and helpful for novice programmers) will be evaluated by ....

Objective 3: (Reduce required time for generating formative assessments for R programming concepts by 90%) will be evaluated by manually writing a selection of assessments and comparing the times required to those assessments generated by AI.

Objective 4.1: (Create a set of 10 - 15 exam questions that cover a range of R programming concepts, techniques, and LLM applications, ensuring that at least 80% of the course material is represented in the questions) will be evaluated by 
Objective 4.2: (Develop a grading rubric with clear criteria for assessing students’ programming proficiency, problem-solving skills, and LLM usage) will be evaluated both by asking students to provide detailed feedback on the rubric as well as using the graded exams to identify which rubrics need refinement. 

## 3.9. Project staff: Employees or students involved in the project and their roles

- Lars: 10%
- Additional Scientific Assisstant at 80 - 100% for 6 to 9 months 

# 4.Sustainability and dissemination

## 4.1.Sustainability: How will project results be maintained and utilised after the funding period? What project results can prospectively be utilised within ETH? Do you need additional funding for this? (265/300 words)

During the funding period, the project will be implemented twice within the same class (rbtl-fs-24: research beyond the lab). Once as a pilot phase evaluated in collaboration with LET. For this, we will work with Nora Dietmann, who will support us in developing a student evaluation survey that explicitly targets the project's objectives. The evaluation results will feed back into re-development course material, implemented once again with our rbtl-fs-25 cohort of students.

We will actively communicate project progress and results at ETH and beyond using several media types and fora (see Section 4.2 Project communication). The project material is published as Open Educational Material with permissive licenses and in an adaptable and reusable format (see Section 4.2 Project Communication & Section 5.2 Accessibility and e-Accessibility). 

This project will last 18 months, and we hope to apply for another Innovedum focal point project on March 1st 2025, which ensures the mid-term continuation of the project for another 18 months from July 2025 to December 2025. The objectives of this second round of funding will primarily focus on rolling out developed modules with identified partners at ETH (e.g., the Computational Competencies initiative, Data Stewardship Network). 

Beyond these three years, utilisation of project results and long-term maintenance is ensured by the fact that the project lead, Lars Schöbitz, holds a permanent contract at the Global Health Engineering research group at D-MAVT. He is not a researcher but holds the position of an administrative technical assistant (Open Science Specialist & Data Steward). The research group is vested in the long-term continuation and scale-up of courses related to this project.

## 4.2. Project communication: How do you plan to publicise and document the progress of the project? What form will the final report for the Innovedum project database take? How will you disseminate project results? (300 words). Info: Interested ETH members should be able to gain insight into the project and the results. How do you ensure this?

As we work by the principles of "open by default", this proposal, progress updates and project outputs are publicized on GitHub with open and permissive licenses to maximize re-use. The course in spring term 2024 (rbtl: Research Beyond the Lab) will have a public website with access to all course materials (slides, exercises, etc.). A project-dedicated website will be developed to highlight aspects unique to the project and share a final report. This report and summaries of it will be published in the Innovedum public project database. 
The project team is part of several initiatives and committees related to open science and data stewardship. We will use these established networks to take the opportunity to present the project at a minimum of two hosted events (e.g. ETH Library Data Stewardship Network Swiss Reproducibility Network Working Groups). 

We will share our first experiences at and contribute to the Innovation Learning & Teaching Fair 2024. Refresh Teaching is another platform and event for which we will prepare material for the greater community.
   
As part of our ETH ORD-funded "openwashdata" program, we send our monthly newsletters to 110 (5% growth/week) people who are interested in the use of open science in the water, sanitation, and hygiene (WASH) sector. Still, we will also highlight this project as it aligns with our overall mission to empower learners of all levels to engage with open science practices. This work will undoubtedly resonate with many members of the community.

We maintain an active GHE LinkedIn account where we frequently highlight the work of our students and our Teaching; we will dedicate a series of posts to this course and it's links to the Innovedum funding

We newly host a blog on our GHE website with monthly posts. We will dedicate several blog posts to this work, especially once the course is finished and we have quantitative data and personal testimonials to report. 

Within GHE, we recently started using the Matrix Chat protocol and Element as our primary communication tool. As ETH offers a Matrix home server, students and staff have direct login access using their ETHZ handle. However, inviting external people to so-called spaces and rooms is also possible. We have started an open room called ghe-open, to which we regularly invite people with a common interest in open science, open research data, etc. This channel can also serve as an opportunity for exchange on AI in Teaching and learning. 

# 5. Data gathering and administration

## 5.1.Will the project involve the gathering of personal data?

No


## 5.2  Accessibility and e-Accessibility: How do you ensure the flexible usability and accessibility of the learning media and materials created in the project? (max ca. 265/300 words) 

As open science advocates, we will publish all learning media and materials as open educational resources. These play a vital role in ensuring flexible usability and accessibility, allowing for the customization and adaptation of content to suit various teaching styles and students' preferences. For instance, our public course website is developed with Quarto open-source scientific and technical publishing system. The underlying code is hosted as a GitHub repository using permissive licenses for all material (e.g. CC-BY-40, MIT License), offering educators a platform to access, modify, share and contribute to educational materials.

We will address all essential e-Accessibility features in our learning materials. (1) Flexible Output: our course website and hosted material are available in HTML file format, allowing for customization of materials in a variety of ways, responsive design, and custom styles. (2) Flexible input: ensured by our course website, all content can be reached using the computer mouse and keyboard. (3) Information & Semantics: Our website will not contain scripted interactive components but will be provided in native HTML and hosted as a static website, ensuring the correct interpretation of content by screen readers. (4) Images and Multimedia: Every used image, prepared diagram, or visualization will be prepared using the alternative text attribute in HTML. We will use decision-making support, such as the Alt-text-Decision-Tree of the Web Accessibility Initiative (WAI), to assess whether the provided text is meaningful and purposeful. We will contact experts at ETH (Anton Bolfing) to check the correctness of alternative texts. (5) Colours and Contrast: We use colorblind-friendly colour palettes in our design andtools to ensure high contrast (e.g. colourcontrast.cc). 


# 6. Funding

## 6.1 Personnel funds

## 6.2 Consumables

## 6.3. Innovedum funds per student (kFr)

## 6.4. Innovedum funds applied for (kFr)

60'000.

# References


