---
title: "Proposal"
format: html
---

# Project idea

- Introduction
    - We are excited to learn that the newest focal point project addition addresses the theme of "AI in Teaching and Learning".
    - I am writing on behalf of the Global Health Engineering group based at D-MAVT, which currently does not have an Educational Developer (though we are in the interviewing phase). I hope it is okay to reach out to you with our project idea.
    - For the first time in FS22, we taught a course that teaches
        - research design,
        - research methods,
        - R statistical programming,
        - use of Git and GitHub for version control and collaboration,
        - scientific writing with Quarto documents,
        - FAIR research data management, and
        - computational reproducibility.
    - We had 12 students of BSc/MSc/PhD levels. We will offer the course again with a limit of 50 students in FS24.
    - This cohort of 50 students would be our testing ground for an Innovedum project on "AI in Teaching and Learning".
- Description of project ideas
    - When introducing novices to a programming language like R, the greatest challenge for students is to find help online. Results of search engines lead to a wealth of resources that are difficult to navigate due to the innovative nature of open source programming languages. This is mostly due to the fact that novices do not know what they are looking for which results in frustration and demotivation to continue learning, or, students use solutions that result in fragmented code that is hard to read and does not use up-to-date best practices.
    - Large language models used by ChatGPT of openAI or perplexity.ai are particularly great at providing coding support. Once students know how to phrase the appropriate prompt, they will receive examples that are both functional, but also coherent in the use of code. The learning experience is significantly improved and students learn how to use AI to their advantage.
    - From the perspective of a lecturer, AI can increase efficiency by providing support in correcting homework coding exercises and specific feedback to students. Further, AI will be tested to provide code for interactive tutorials that are otherwise difficult to design.
    - Lastly, students will learn how to use AI to develop a research design and research methods for a given topic. AI will support their literature review and note-taking process.


# Project proposal
